import Head from 'next/head'
import  Link  from 'next/link'

const Home = ({holidays}) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <ol>
        {holidays.map((holiday) =>
          // holidays/2021-01-01
          <li key={holiday.date}><Link href={`holidays/${holiday.date}`}>{holiday.date}</Link></li>
        )}
      </ol>
      </main>

      <footer>
      </footer>
    </div>
  )
}

export const getStaticProps = async () => {
  const response = await fetch('https://gov.uk/bank-holidays.json')
  const holidaysJson = await response.json()

  return {
    props: {
      holidays: holidaysJson['england-and-wales']['events']
    }
  }
}

export default Home
