import Head from 'next/head'
import  Link  from 'next/link'

const Neil = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <h1>Neil</h1>
      </main>

      <footer>
      </footer>
    </div>
  )
}

export default Neil
